In [2]:
import pandas as pd
import numpy as numpy

In [3]:
df = pd.read_csv('train_ver2.csv')

/var/folders/2d/pf4vpln94mx48vzbwvk5m9mw0000gp/T/ipykernel_49545/1621394854.py:1: DtypeWarning: Columns (5,8,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('train_ver2.csv')

In [4]:
df

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
0,2015-01-28,1375586,N,ES,H,35,2015-01-12,0.0,6,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
1,2015-01-28,1050611,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
2,2015-01-28,1050612,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
3,2015-01-28,1050613,N,ES,H,22,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
4,2015-01-28,1050614,N,ES,V,23,2012-08-10,0.0,35,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13647304,2016-05-28,1166765,N,ES,V,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647305,2016-05-28,1166764,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647306,2016-05-28,1166763,N,ES,H,47,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647307,2016-05-28,1166789,N,ES,H,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0
13647308,2016-05-28,1550586,N,ES,H,37,2016-05-13,1.0,0,1.0,...,0,0,0,0,0,0,0,0.0,0.0,0

# 1

In [5]:
df_lastday=df.loc[df['fecha_dato'] == '2016-05-28']
df_lastday['고객수']=1
df_lastday

/var/folders/2d/pf4vpln94mx48vzbwvk5m9mw0000gp/T/ipykernel_49545/4287283245.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lastday['고객수']=1

,fecha_dato,ncodpers,ind_empleado,pais_residencia,sexo,age,fecha_alta,ind_nuevo,antiguedad,indrel,...,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1,고객수
12715856,2016-05-28,657640,N,ES,H,68,2006-11-17,0.0,114,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1
12715857,2016-05-28,657788,N,ES,H,42,2006-11-18,0.0,114,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1
12715858,2016-05-28,657795,N,ES,V,44,2006-11-18,0.0,114,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1
12715859,2016-05-28,657790,N,ES,V,42,2006-11-18,0.0,114,1.0,...,0,0,0,1,0,0,1.0,1.0,1,1
12715860,2016-05-28,657794,N,ES,H,49,2006-11-18,0.0,114,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13647304,2016-05-28,1166765,N,ES,V,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1
13647305,2016-05-28,1166764,N,ES,V,23,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1
13647306,2016-05-28,1166763,N,ES,H,47,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1
13647307,2016-05-28,1166789,N,ES,H,22,2013-08-14,0.0,33,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1
13647308,2016-05-28,1550586,N,ES,H,37,2016-05-13,1.0,0,1.0,...,0,0,0,0,0,0,0.0,0.0,0,1

In [6]:
df_lastday = df_lastday.drop(columns=[
                                      "ind_nuevo","antiguedad","indrel","ult_fec_cli_1t","indrel_1mes","tiprel_1mes","indresi","indext","conyuemp",
                                      "ind_ahor_fin_ult1","ind_aval_fin_ult1","ind_cco_fin_ult1","ind_cder_fin_ult1","ind_cno_fin_ult1","ind_ctju_fin_ult1",
                                      "ind_ctma_fin_ult1","ind_ctop_fin_ult1","ind_ctpp_fin_ult1","ind_deco_fin_ult1","ind_deme_fin_ult1","ind_dela_fin_ult1",
                                      "ind_ecue_fin_ult1","ind_fond_fin_ult1","ind_hip_fin_ult1","ind_plan_fin_ult1","ind_pres_fin_ult1","ind_reca_fin_ult1",
                                      "ind_tjcr_fin_ult1","ind_valo_fin_ult1","ind_viv_fin_ult1","ind_nomina_ult1","ind_nom_pens_ult1","ind_recibo_ult1"
                                      ])
#df_lastday

In [7]:
result=df_lastday.groupby('nomprov')[['고객수']].sum()

result['평균소득']=df_lastday.groupby('nomprov')['renta'].mean()
result['소득중앙값']=df_lastday.groupby('nomprov')['renta'].median()
result['평균나이']=df_lastday.groupby('nomprov')['age'].mean()

result

                           고객수           평균소득       소득중앙값       평균나이
nomprov
ALAVA                     2597  132838.933333  103321.140  46.090104
ALBACETE                  7792   82970.140154   78566.325  32.976771
ALICANTE                 22210   87142.959076   67332.870  38.883116
ALMERIA                   4317   84851.186250   72932.925  40.165393
ASTURIAS                 18332  101311.341324   87085.140  38.950524
AVILA                     2632   76155.498608   67509.345  36.402736
BADAJOZ                  12949   72130.066952   62307.675  31.073442
BALEARS, ILLES            9143  171890.951564  122837.220   39.74877
BARCELONA                88754  164584.843157  130877.160  39.865144
BIZKAIA                  12528  110828.564000   97637.505  51.057391
BURGOS                    6660   97780.229124   89299.890  38.092042
CACERES                   8605   75454.406775   67716.000  31.451017
CADIZ                    19829   98772.353515   79068.720   35.83156
CANTABRIA                10843  121170.217007   95250.510   41.30047
CASTELLON                 7168   79028.432511   66454.080  35.766741
CEUTA                      513  200515.885152  128699.580  44.007797
CIUDAD REAL               8096   70008.773617   62213.970   33.73876
CORDOBA                   9857   85811.520086   69069.090  36.069697
CORUÑA, A                28771  112581.079748   97389.315  33.799103
CUENCA                    3793   69748.533755   66539.715  32.890852
GIPUZKOA                  4887  127185.417857   87024.930  48.131164
GIRONA                    6313  145193.823741  108908.340  36.125297
GRANADA                  12426   96544.954543   82354.560  38.388379
GUADALAJARA               4695   95403.940147   92483.205  40.076464
HUELVA                    8032   76732.887707   68897.520  33.397037
HUESCA                    2795   89253.640457   73531.980  36.062612
JAEN                      4509   76996.493517   67777.635  40.488357
LEON                      5731   93490.714165   80953.410  42.878555
LERIDA                    5439   81517.969975   64772.640  33.566281
LUGO                      5670   76458.005733   64304.880   31.53545
MADRID                  298841  178362.993637  138024.135  45.205564
MALAGA                   24583  120920.857735   94961.910  38.502298
MELILLA                    641  149071.944149  117718.365  45.329173
MURCIA                   27795   78943.243629   67794.735  31.878683
NAVARRA                   6023  114208.460625   83410.935  44.020588
OURENSE                   5615   83135.325995   79009.830  31.565806
PALENCIA                  3319   93114.083452   86602.185  35.424827
PALMAS, LAS              16361  100171.383055   80591.610   37.62325
PONTEVEDRA               18990  113397.605584   97699.890   32.61227
RIOJA, LA                 5816   99366.831511   89486.910  41.501891
SALAMANCA                11093  105520.396300   89750.880  34.524745
SANTA CRUZ DE TENERIFE    5119  102131.308182   82331.550  44.650713
SEGOVIA                   2881   98794.885055   89524.470  38.437348
SEVILLA                  40581  117368.868903   92369.460  38.164806
SORIA                     1261   87837.921027   78559.230   38.49088
TARRAGONA                 7650  104479.600944   87640.425  37.742745
TERUEL                    1538   88168.578000   76778.040  32.584525
TOLEDO                   12690   80116.487937   68747.730  35.999921
VALENCIA                 48103   89296.188278   72734.910  39.106854
VALLADOLID               16044  101641.794166   92628.285  38.150087
ZAMORA                    3433   83752.301334   74767.500  33.491407
ZARAGOZA                 23198  110172.519208   99607.890  41.006035

In [8]:
result=result.loc[result['고객수'] >= 50]
result

                           고객수           평균소득       소득중앙값       평균나이
nomprov
ALAVA                     2597  132838.933333  103321.140  46.090104
ALBACETE                  7792   82970.140154   78566.325  32.976771
ALICANTE                 22210   87142.959076   67332.870  38.883116
ALMERIA                   4317   84851.186250   72932.925  40.165393
ASTURIAS                 18332  101311.341324   87085.140  38.950524
AVILA                     2632   76155.498608   67509.345  36.402736
BADAJOZ                  12949   72130.066952   62307.675  31.073442
BALEARS, ILLES            9143  171890.951564  122837.220   39.74877
BARCELONA                88754  164584.843157  130877.160  39.865144
BIZKAIA                  12528  110828.564000   97637.505  51.057391
BURGOS                    6660   97780.229124   89299.890  38.092042
CACERES                   8605   75454.406775   67716.000  31.451017
CADIZ                    19829   98772.353515   79068.720   35.83156
CANTABRIA                10843  121170.217007   95250.510   41.30047
CASTELLON                 7168   79028.432511   66454.080  35.766741
CEUTA                      513  200515.885152  128699.580  44.007797
CIUDAD REAL               8096   70008.773617   62213.970   33.73876
CORDOBA                   9857   85811.520086   69069.090  36.069697
CORUÑA, A                28771  112581.079748   97389.315  33.799103
CUENCA                    3793   69748.533755   66539.715  32.890852
GIPUZKOA                  4887  127185.417857   87024.930  48.131164
GIRONA                    6313  145193.823741  108908.340  36.125297
GRANADA                  12426   96544.954543   82354.560  38.388379
GUADALAJARA               4695   95403.940147   92483.205  40.076464
HUELVA                    8032   76732.887707   68897.520  33.397037
HUESCA                    2795   89253.640457   73531.980  36.062612
JAEN                      4509   76996.493517   67777.635  40.488357
LEON                      5731   93490.714165   80953.410  42.878555
LERIDA                    5439   81517.969975   64772.640  33.566281
LUGO                      5670   76458.005733   64304.880   31.53545
MADRID                  298841  178362.993637  138024.135  45.205564
MALAGA                   24583  120920.857735   94961.910  38.502298
MELILLA                    641  149071.944149  117718.365  45.329173
MURCIA                   27795   78943.243629   67794.735  31.878683
NAVARRA                   6023  114208.460625   83410.935  44.020588
OURENSE                   5615   83135.325995   79009.830  31.565806
PALENCIA                  3319   93114.083452   86602.185  35.424827
PALMAS, LAS              16361  100171.383055   80591.610   37.62325
PONTEVEDRA               18990  113397.605584   97699.890   32.61227
RIOJA, LA                 5816   99366.831511   89486.910  41.501891
SALAMANCA                11093  105520.396300   89750.880  34.524745
SANTA CRUZ DE TENERIFE    5119  102131.308182   82331.550  44.650713
SEGOVIA                   2881   98794.885055   89524.470  38.437348
SEVILLA                  40581  117368.868903   92369.460  38.164806
SORIA                     1261   87837.921027   78559.230   38.49088
TARRAGONA                 7650  104479.600944   87640.425  37.742745
TERUEL                    1538   88168.578000   76778.040  32.584525
TOLEDO                   12690   80116.487937   68747.730  35.999921
VALENCIA                 48103   89296.188278   72734.910  39.106854
VALLADOLID               16044  101641.794166   92628.285  38.150087
ZAMORA                    3433   83752.301334   74767.500  33.491407
ZARAGOZA                 23198  110172.519208   99607.890  41.006035

In [9]:
result=result.sort_values(by='평균소득', ascending=False)
result.iloc[:5]
#result

                   고객수           평균소득       소득중앙값       평균나이
nomprov
CEUTA              513  200515.885152  128699.580  44.007797
MADRID          298841  178362.993637  138024.135  45.205564
BALEARS, ILLES    9143  171890.951564  122837.220   39.74877
BARCELONA        88754  164584.843157  130877.160  39.865144
MELILLA            641  149071.944149  117718.365  45.329173

# 2

In [14]:
products = df.columns[24:48]
products

Index(['ind_ahor_fin_ult1', 'ind_aval_fin_ult1', 'ind_cco_fin_ult1',
       'ind_cder_fin_ult1', 'ind_cno_fin_ult1', 'ind_ctju_fin_ult1',
       'ind_ctma_fin_ult1', 'ind_ctop_fin_ult1', 'ind_ctpp_fin_ult1',
       'ind_deco_fin_ult1', 'ind_deme_fin_ult1', 'ind_dela_fin_ult1',
       'ind_ecue_fin_ult1', 'ind_fond_fin_ult1', 'ind_hip_fin_ult1',
       'ind_plan_fin_ult1', 'ind_pres_fin_ult1', 'ind_reca_fin_ult1',
       'ind_tjcr_fin_ult1', 'ind_valo_fin_ult1', 'ind_viv_fin_ult1',
       'ind_nomina_ult1', 'ind_nom_pens_ult1', 'ind_recibo_ult1'],
      dtype='object')

In [15]:
dates = df.groupby('fecha_dato')[['ncodpers']].sum()
dates=dates.index
dates

Index(['2015-01-28', '2015-02-28', '2015-03-28', '2015-04-28', '2015-05-28',
       '2015-06-28', '2015-07-28', '2015-08-28', '2015-09-28', '2015-10-28',
       '2015-11-28', '2015-12-28', '2016-01-28', '2016-02-28', '2016-03-28',
       '2016-04-28', '2016-05-28'],
      dtype='object', name='fecha_dato')

In [16]:
names = {}
for product in products:
    names[product] = product + '_prev'
names

{'ind_ahor_fin_ult1': 'ind_ahor_fin_ult1_prev',
 'ind_aval_fin_ult1': 'ind_aval_fin_ult1_prev',
 'ind_cco_fin_ult1': 'ind_cco_fin_ult1_prev',
 'ind_cder_fin_ult1': 'ind_cder_fin_ult1_prev',
 'ind_cno_fin_ult1': 'ind_cno_fin_ult1_prev',
 'ind_ctju_fin_ult1': 'ind_ctju_fin_ult1_prev',
 'ind_ctma_fin_ult1': 'ind_ctma_fin_ult1_prev',
 'ind_ctop_fin_ult1': 'ind_ctop_fin_ult1_prev',
 'ind_ctpp_fin_ult1': 'ind_ctpp_fin_ult1_prev',
 'ind_deco_fin_ult1': 'ind_deco_fin_ult1_prev',
 'ind_deme_fin_ult1': 'ind_deme_fin_ult1_prev',
 'ind_dela_fin_ult1': 'ind_dela_fin_ult1_prev',
 'ind_ecue_fin_ult1': 'ind_ecue_fin_ult1_prev',
 'ind_fond_fin_ult1': 'ind_fond_fin_ult1_prev',
 'ind_hip_fin_ult1': 'ind_hip_fin_ult1_prev',
 'ind_plan_fin_ult1': 'ind_plan_fin_ult1_prev',
 'ind_pres_fin_ult1': 'ind_pres_fin_ult1_prev',
 'ind_reca_fin_ult1': 'ind_reca_fin_ult1_prev',
 'ind_tjcr_fin_ult1': 'ind_tjcr_fin_ult1_prev',
 'ind_valo_fin_ult1': 'ind_valo_fin_ult1_prev',
 'ind_viv_fin_ult1': 'ind_viv_fin_ult1_prev',
 'ind_nomina_ult1': 'ind_nomina_ult1_prev',
 'ind_nom_pens_ult1': 'ind_nom_pens_ult1_prev',
 'ind_recibo_ult1': 'ind_recibo_ult1_prev'}

In [17]:
result = []


for i in range(1, len(dates)):

    # 전번달
    previous = df.loc[
        df['fecha_dato'] == dates[i - 1]
    ].set_index('ncodpers')[products]

    # 이번달
    current = df.loc[
        df['fecha_dato'] == dates[i]
    ].set_index('ncodpers')[products]

    previous = previous.rename(columns=names)

    # 연결
    compared = current.join(previous)

    for product in products:
        new_count = (
            (compared[product + '_prev'] == 0)
            & (compared[product] == 1)
        ).sum()

        result.append({
            'fecha_dato': dates[i],
            '상품': product,
            '신규가입건수': new_count
        })
result

[{'fecha_dato': '2015-02-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(1)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(1)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(2132)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(12)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(1884)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(7)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(291)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(249)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(171)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(348)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(33)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(724)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1472)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(451)},
 {'fecha_dato': '2015-02-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(5)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(27)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(9)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(217)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(3471)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(259)},
 {'fecha_dato': '2015-02-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(8)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(5659)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(5656)},
 {'fecha_dato': '2015-02-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(8285)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(1)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(2293)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(15)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(1786)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(18)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(272)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(284)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(165)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(481)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(23)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(814)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1594)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(570)},
 {'fecha_dato': '2015-03-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(7)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(24)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(12)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(217)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(5076)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(205)},
 {'fecha_dato': '2015-03-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(4)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(4479)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(4473)},
 {'fecha_dato': '2015-03-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(9135)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(1)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(2366)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(12)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(1984)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(10)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(217)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(278)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(167)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(263)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(26)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(775)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1459)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(492)},
 {'fecha_dato': '2015-04-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(4)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(22)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(17)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(871)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(4627)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(194)},
 {'fecha_dato': '2015-04-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(5)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(2663)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(5628)},
 {'fecha_dato': '2015-04-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(8346)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(2264)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(7)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(1900)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(10)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(205)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(289)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(172)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(238)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(25)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(885)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1461)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(396)},
 {'fecha_dato': '2015-05-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(9)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(21)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(11)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(343)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(4071)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(201)},
 {'fecha_dato': '2015-05-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(4)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(3369)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(3345)},
 {'fecha_dato': '2015-05-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(7085)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(6588)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(9)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(1857)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(7)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(210)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(213)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(151)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(289)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(33)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(939)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1204)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(245)},
 {'fecha_dato': '2015-06-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(4)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(19)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(8)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(2931)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(4655)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(152)},
 {'fecha_dato': '2015-06-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(3)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(5070)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(8135)},
 {'fecha_dato': '2015-06-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(9023)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(3056)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(10)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(2771)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(18)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(191)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(252)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(164)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(265)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(24)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(1138)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1085)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(204)},
 {'fecha_dato': '2015-07-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(6)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(27)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(5)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(589)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(4886)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(232)},
 {'fecha_dato': '2015-07-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(9)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(4408)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(4850)},
 {'fecha_dato': '2015-07-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(9172)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(5730)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(10)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(2412)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(37)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(240)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(231)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(145)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(322)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(33)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(1024)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(924)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(223)},
 {'fecha_dato': '2015-08-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(1)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(22)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(13)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(264)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(4379)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(445)},
 {'fecha_dato': '2015-08-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(2)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(2950)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(2968)},
 {'fecha_dato': '2015-08-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(7115)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(4389)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(7)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(1775)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(22)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(471)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(191)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(122)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(387)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(30)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(1348)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1072)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(130)},
 {'fecha_dato': '2015-09-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(8)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(21)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(13)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(271)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(4463)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(328)},
 {'fecha_dato': '2015-09-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(2)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(4683)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(4753)},
 {'fecha_dato': '2015-09-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(11210)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(5682)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(3)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(2409)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(43)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(468)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(223)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(153)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(349)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(22)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(1390)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1205)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(146)},
 {'fecha_dato': '2015-10-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(7)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(19)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_pres_fin_ult1',
  '신규가입건수': np.int64(9)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_reca_fin_ult1',
  '신규가입건수': np.int64(593)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_tjcr_fin_ult1',
  '신규가입건수': np.int64(4461)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_valo_fin_ult1',
  '신규가입건수': np.int64(911)},
 {'fecha_dato': '2015-10-28', '상품': 'ind_viv_fin_ult1', '신규가입건수': np.int64(2)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_nomina_ult1',
  '신규가입건수': np.int64(4818)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_nom_pens_ult1',
  '신규가입건수': np.int64(4790)},
 {'fecha_dato': '2015-10-28',
  '상품': 'ind_recibo_ult1',
  '신규가입건수': np.int64(12100)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_ahor_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_aval_fin_ult1',
  '신규가입건수': np.int64(0)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_cco_fin_ult1',
  '신규가입건수': np.int64(4670)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_cder_fin_ult1',
  '신규가입건수': np.int64(6)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_cno_fin_ult1',
  '신규가입건수': np.int64(2930)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_ctju_fin_ult1',
  '신규가입건수': np.int64(31)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_ctma_fin_ult1',
  '신규가입건수': np.int64(633)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_ctop_fin_ult1',
  '신규가입건수': np.int64(209)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_ctpp_fin_ult1',
  '신규가입건수': np.int64(140)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_deco_fin_ult1',
  '신규가입건수': np.int64(110)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_deme_fin_ult1',
  '신규가입건수': np.int64(1)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_dela_fin_ult1',
  '신규가입건수': np.int64(908)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_ecue_fin_ult1',
  '신규가입건수': np.int64(1588)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_fond_fin_ult1',
  '신규가입건수': np.int64(169)},
 {'fecha_dato': '2015-11-28', '상품': 'ind_hip_fin_ult1', '신규가입건수': np.int64(3)},
 {'fecha_dato': '2015-11-28',
  '상품': 'ind_plan_fin_ult1',
  '신규가입건수': np.int64(37)},
 {'fecha_dato': '2015-11-28',

In [18]:
monthly_result = pd.DataFrame(result)
monthly_result

     fecha_dato                 상품  신규가입건수
0    2015-02-28  ind_ahor_fin_ult1       1
1    2015-02-28  ind_aval_fin_ult1       1
2    2015-02-28   ind_cco_fin_ult1    2132
3    2015-02-28  ind_cder_fin_ult1      12
4    2015-02-28   ind_cno_fin_ult1    1884
..          ...                ...     ...
379  2016-05-28  ind_valo_fin_ult1     183
380  2016-05-28   ind_viv_fin_ult1       7
381  2016-05-28    ind_nomina_ult1    5488
382  2016-05-28  ind_nom_pens_ult1    5513
383  2016-05-28    ind_recibo_ult1   10163

[384 rows x 3 columns]

In [19]:
total_result = monthly_result.groupby('상품')[['신규가입건수']].sum()
total_result = total_result.sort_values(by='신규가입건수', ascending=False)
#total_result
total_result.iloc[:5]

                   신규가입건수
상품
ind_recibo_ult1    153146
ind_nom_pens_ult1   84709
ind_nomina_ult1     73753
ind_tjcr_fin_ult1   69118
ind_cco_fin_ult1    69103

# 3

In [20]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [23]:
columns = [
    'sexo', 'age', 'segmento', 'ind_empleado', 'tiprel_1mes'
] + list(products)

last = df.loc[df['fecha_dato'] == '2016-05-28', columns]
#last
#triple_1mes에 NaN값 존재
last = last.dropna()

In [24]:
last['상품수'] = last[products].sum(axis=1)
last['가입여부'] = 0
last.loc[last['상품수'] >= 3, '가입여부'] = 1

In [27]:
last.loc[last['age'] < 30, '연령대'] = 'young'
last.loc[last['age'] >= 30, '연령대'] = 'adult'
last.loc[last['age'] >= 65, '연령대'] = 'senior'

In [29]:
criteria = [
    'sexo', '연령대', 'segmento', 'ind_empleado', 'tiprel_1mes'
]

y = last['가입여부']

results = []

for criterion in criteria:

    X = pd.get_dummies(last[criterion])

    #점수 계산
    bestfeatures = SelectKBest(score_func=chi2, k='all')
    fit = bestfeatures.fit(X, y)

    score = fit.scores_.sum()

    results.append({
        '기준': criterion,
        '카이제곱': score
    })

result = pd.DataFrame(results)
result = result.sort_values(by='카이제곱', ascending=False)

result

             기준           카이제곱
4   tiprel_1mes  184979.998993
2      segmento  124374.223984
1           연령대   61536.478399
0          sexo    3443.992615
3  ind_empleado    1336.294946